version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run: sh ./deploy/run.sh
workflows:
  deploy:
    jobs:
      - deploy
